### PR TITLE
circus.ini - taiga-events: coffee command path fixed

### PR DESCRIPTION
**Pull request by ygorth**
Events won't work if user does not have coffee in /usr/local/bin/.

### CODE REVIEW

**Comment by bameda** [comment]
I don't need this fix in my machine:

```
> cd taiga-events
> type -a coffee
coffee is /home/bameda/.nvm/versions/node/v5.0.0/bin/coffee
> coffee index.coffee

```

**Comment by ygorth** [comment]
Hi @bameda,

Please, take a look in my output:

taiga@scrum:~/taiga-events$ whereis coffee
coffee:
- or -
taiga@scrum:~/taiga-events$ type -a coffee
-bash: type: coffee: not found


taiga@scrum:~/taiga-events$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
...

I am pretty sure I've followed all the steps. Did you do some 'extra' step to have your current environment like that?

**Comment by bameda** [comment]
Ok, the docu say you have to use sudo to install coffee-script

```
 sudo npm install -g coffee-script
```

So you have to install it in the taiga home with:

```
npm install -g coffee-script
```

**Comment by ygorth** [comment]
Hey guys,

I made a mistake I forgot about install coffeescript using npm. Now everything works fine now. My bad, thanks!

**Comment by bameda** [comment]
Ummmm is obvious that there is a mistake in the doc. I find this funny commit: 

https://github.com/ygorth/taiga-doc/commit/0d9e5ab802281cf64d651cb599a85e7d8b0ff3ba

So, or we don't use sudo to install coffee-script or we have to change the path to /usr/local.

I'll talk about this with  the team tomorrow morning in the daily meeting.

**Comment by bameda** [comment]
Ok, our doc is ok. Is your fork the one who has the mistake.

**Pull request closed without merging**
