### PR TITLE
Fix typo in wiki create-attachment

### PR DESCRIPTION
**Pull request by astagi**

### CODE REVIEW

**Comment by bameda** [comment]
Thanks @astagi.

Your other PR are pending and we'll try to merge the next week.

**Comment by astagi** [comment]
yw :) 

oh no problem, at the moment I have no pending PR, they were merged yesterday! :) :)

**Comment by bameda** [comment]
o_O you're right, I had not realized

**Comment by astagi** [comment]
:) no problem!

**Pull request merged**
