### PR TITLE
Fix bash issues (variables in single quotes, escaping &) and some typos

### PR DESCRIPTION
**Pull request by myii**
Please see full commit messages for details.

### CODE REVIEW

**Comment by bameda** [comment]
Good work. \o/

Thanks @myii.

**Comment by myii** [comment]
Don't mention it.  In reality, you all deserve thanks for such an excellent product.

One more issue, re: section __1.1. Authentication__.  Since `${AUTH_TOKEN}` is used throughout the API calls, would it be helpful to provide a bash snippet to extract this from the login API?  I can provide this if it is worthwhile.

**Comment by superalex** [comment]
Thanks @myii I think it could be really useful :)

**Comment by myii** [comment]
Done - please see https://github.com/taigaio/taiga-doc/pull/18

Hope it is useful... and thanks again!

**Comment by superalex** [comment]
Thank you very much @myii

**Pull request merged**
