### PR TITLE
Configure Guardfile to enable live preview in browser

### PR DESCRIPTION
**Pull request by myii**
* Editing *.adoc files without live preview in the browser is tedious
* Guard is one of the recommended methods suggested for AsciiDoc:
http://asciidoctor.org/docs/editing-asciidoc-with-live-preview/
* This proposed Guardfile simply extracts the commands from the Makefile
and builds the html files as soon as one of the source adoc files has
been modified
* If this method is too "magical", can simply duplicate the lines from
the Makefile in the Guardfile instead
* Live preview is achieved when coupled with the other required
components

Follow-up to #25

### CODE REVIEW

**Comment by myii** [comment]
@superalex Would you like me to provide my configuration to get this working?  I'm going to be busy for a while but I'll see what I can put together if you are interested.

**Comment by superalex** [comment]
I finally could install guard and works great. Could you add a small README update for usersg who want to use the guard feature to the PR please?

**Comment by myii** [comment]
OK, but I won't be able to get back around to this until later.  Hopefully later today. Glad to hear you've got it working.

**Comment by superalex** [comment]
No problem :)

And thank you very very much!

**Comment by myii** [comment]
@superalex: STOP! I'm really not thinking straight at the moment... forgot to rebase before pushing.  Please let me complete that before you merge...

**Comment by myii** [comment]
@superalex: OK, all done, very sorry about that.  Hope the contribution is useful.

**Comment by myii** [comment]
@superalex: Cleaning up at my end and I've just realised that I've squashed over the original commit for this PR.  Too much work, too little sleep... really sorry, is it still OK for you to work with or shall we start over?  This is embarrassing...

**Comment by superalex** [comment]
@myii don't worry, your contribution is really useful, we (the development team) have been talking about it and we think it's great. 

I think the PR is ready to be merged but I also I like the idea of adding a reminder in Makefile, it's the typical thing you forget to add :), would you like to add it before merging?

Thanks! ;)

**Comment by myii** [comment]
@superalex: There we go... I managed to push the commit this time without breaking the previous (broken) one!  I'm very glad that it has been helpful to you all - that's the least I could do after such a wonderful product.  In fact, I have further reason to be ashamed since I could have shared this with you some time back but I have been very busy!  I'll catch up to you on the mailing list soon because I have a question or two to ask.  Keep up the excellent work!

**Comment by superalex** [comment]
Thank you very much @myii :)

We'll be waiting for you in the mailing list!

**Pull request merged**
