### PR TITLE
Implementing Multi-level Push Menu

### PR DESCRIPTION
**Pull request by wongalvis**

### CODE REVIEW

**Comment by wongalvis** [comment]
The necessary CSS, fonts and JS files are included in the PR for gh-pages branch https://github.com/taigaio/taiga-doc/pull/54

**Comment by superalex** [comment]
Hello @wongalvis,

Thank you very much for your pull request. I couldn't make it work.

I had to install a gem called thread_safe, could you add any dependencies in your pull request please?

After installing it and trying to compile:

```
make
asciidoctor -T custom-html5 -o dist/index.html index.adoc
cannot load such file -- haml
  Use --trace for backtrace
Makefile:29: recipe for target 'doc' failed
make: *** [doc] Error 1
```

No code should be added to dist folder, this folder should be auto generated all the time and it's ignored by the .ignore file. So your other pull request shouldn't include it.

**Comment by wongalvis** [comment]
@superalex They are the CSS, fonts and JS files to be included at that directory.

**Comment by superalex** [comment]
Yes, the make process should finish with that files on that folder but that folder is deleted when executing build-docs.sh so they can't be there from the beginning...

**Comment by wongalvis** [comment]
I'll look into that, it's kinda late here.

**Comment by superalex** [comment]
Hello @wongalvis, 

Github support a special branch called gh-pages for the project pages -> https://help.github.com/articles/creating-project-pages-manually/

build-docs.sh is a bash script that executes the compiles the html pages and updates them correctly in the gh-pages branch.

**Comment by wongalvis** [comment]
I mean the syntax of commands inside.

**Comment by superalex** [comment]
tests/check_JSON_trailing_commas.sh
#Checking if the included json haven't bad commas

make || exit 1
#Compile the html pages (generates the dist folder)

rm -rf /tmp/taiga-doc-dist || exit 1
#Delete the /tmp/taiga-doc-dist folder

cp -r dist /tmp/taiga-doc-dist || exit 1
#Copy the generated dist from "make" to /tmp/taiga-doc-dist

git checkout gh-pages || exit 1
#Checkout to gh-pages branch

rm -rf dist || exit 1
#Remove the dist folder
mv /tmp/taiga-doc-dist dist || exit 1
#Moves the /tmp/taiga-doc-dist created folder (containing the results of make in master branch) and moves to dist folder

git add --all dist || exit 1
#Add all changes on dist to the current commit 

git commit -a -m "Update doc" || exit 1
#Creates the commit for the repo

**Comment by wongalvis** [comment]
Would including haml gem fix the issue upon generating html files?

**Comment by wongalvis** [comment]
If I put the CSS, fonts and JS under a folder called assets/
The command should be:
cp -r assets/ /tmp/taiga-doc-dist || exit 1
or cp -r assets /tmp/taiga-doc-dist || exit 1

**Comment by superalex** [comment]
It depends, I think the first one will copy only the assets content and the second one the assets folders

**Comment by wongalvis** [comment]
@superalex I think the one modified just now https://github.com/wongalvis/taiga-doc/commit/baf32503716efe55c8d178694c1a0cb65c2a294b should be right.

**Comment by superalex** [comment]
Sorry @wongalvis, probably I didn't explain it right,

I think that cp should be included in the Makefile, not in the build-docs.sh , now if I only execute the make command the generated dist folder (for example because I'm writing new doc and want to check how it look) the result doesn't include the js and css needed files. 

Could you please add the haml installation to the README please?

**Comment by wongalvis** [comment]
Indeed I just followed the instructions on installing asciidoctor so I have no idea about installing haml separately.

**Comment by superalex** [comment]
Sorry @wongalvis but the updated Makefile doesn't work, did you try to execute it?

```
make
Makefile:27: *** missing separator.  Stop.
```

About the haml installation, for the pull request to be complete it should also include doc about the installation of the required gems (in the README file), I think they are thread_safe and haml. Including the "gem install XXXX" would be enough.

Regards,

**Comment by wongalvis** [comment]
About the makefile, it should be a syntax error, indeed I have no knowledge about the syntax. Sorry.

**Comment by wongalvis** [comment]
And where (which part of the README) should I add the gem install xxx to.

**Comment by superalex** [comment]
For working properly the content of the Makefile should finish with something like:

all: doc
doc:
	asciidoctor -T custom-html5 -o dist/index.html index.adoc
	asciidoctor -T custom-html5 -o dist/setup-production.html setup-production.adoc
	asciidoctor -T custom-html5 -o dist/setup-development.html setup-development.adoc
	asciidoctor -T custom-html5 -o dist/setup-alternatives.html setup-alternatives.adoc
	asciidoctor -T custom-html5 -o dist/api.html api/api.adoc
	asciidoctor -T custom-html5 -o dist/webhooks.html webhooks.adoc
	cp -r assets/* dist  || exit 1

**Comment by superalex** [comment]
The best part for the README would be where it says "gem install bundler" after that line you could add the other required gems installation.

Regards,

**Comment by wongalvis** [comment]
It should be 
`all: doc
doc:
	asciidoctor -T custom-html5 -o dist/index.html index.adoc
	asciidoctor -T custom-html5 -o dist/setup-production.html setup-production.adoc
	asciidoctor -T custom-html5 -o dist/setup-development.html setup-development.adoc
	asciidoctor -T custom-html5 -o dist/setup-alternatives.html setup-alternatives.adoc
	asciidoctor -T custom-html5 -o dist/api.html api/api.adoc
	asciidoctor -T custom-html5 -o dist/webhooks.html webhooks.adoc
cp -r assets/ dist || exit 1`
or
`all: doc
doc:
asciidoctor -T custom-html5 -o dist/index.html index.adoc
asciidoctor -T custom-html5 -o dist/setup-production.html setup-production.adoc
asciidoctor -T custom-html5 -o dist/setup-development.html setup-development.adoc
asciidoctor -T custom-html5 -o dist/setup-alternatives.html setup-alternatives.adoc
asciidoctor -T custom-html5 -o dist/api.html api/api.adoc
asciidoctor -T custom-html5 -o dist/webhooks.html webhooks.adoc
cp -r assets/ dist || exit 1`

**Comment by superalex** [comment]
The two blocks are the same... :)

**Comment by wongalvis** [comment]
Updated. :)

**Comment by superalex** [comment]
@wongalvis the Make file isn't working...it should include "cp -r assets/* dist || exit 1", did you try to remove the dist folder and create it again with the make file?

Regards,

**Comment by wongalvis** [comment]
It should be correct now.

**Comment by superalex** [comment]
Thanks @wongalvis now the make works correctly.

Testing the API doc  (from the index go to API doc) I found an issue:

taiga

The menu that can't be shown is in gray color and if I select one of those entries the result is strange:

taiga

**Comment by wongalvis** [comment]
Can you send me the adoc you're using?

**Comment by superalex** [comment]
Just the ones from taiga-doc repo...

Execute tha make, browse the index.html, select 3.API and follow the link "check the full API documentation here."

**Comment by wongalvis** [comment]
A temporary workaround with a drawback that when the menu is clicked it scrolls to top in order to view the content in submenu properly.

**Comment by superalex** [comment]
Thanks @wongalvis,

I think it's working ok now, before merging your pull request, could you please squash your six commits in just one?. The repo will be cleaner when merging and if we have any problem it would be easier to revert.

Thanks.

**Comment by wongalvis** [comment]
I don't really agree that it is a good idea since the first commit is implementing the multi-level push menu as original as it could regarding to the source from Codrops. Each of the commits is representing a new set of work done, I think it would be better to keep them separated that it would be easier to fix issues.

**Comment by superalex** [comment]
The problem is that if we use the six commits the feature is less "pluggable" and we would prefer it to be that way. One commit wouldn't be too big and all the work is related to the same feature ;)

**Comment by wongalvis** [comment]
Ok, understood and updated. :)

**Comment by superalex** [comment]
Merged!, thank you very much @wongalvis :+1:

**Pull request merged**
