### PR TITLE
Notify re: JSON trailing commas using new Guardfile, Guard run through b...

### PR DESCRIPTION
**Pull request by myii**
...undle

* Overview: Using Guard to run test and show notifications
* Need to install Guard according to official instructions from:
  https://github.com/guard/guard#readme:
  "It's important that you always run Guard through Bundler to avoid errors."
* New script to perform check for JSON trailing commas; used in 2 ways:
  1. Guard => file just modified
  2. build-docs.sh => check all .adoc files in taiga-doc (warnings, no exit)
* Guardfile improvements:
  - Works with new .adoc files automatically
  - Notifies user where a match in Makefile is not found
  - Works with multiple line matches in Makefile
  - Centralised into 1 watch so much easier to add more tests or make changes

### Next steps
@jespino @superalex 
* If following through with this PR, README.md needs to be updated with the new `bundle`-based instructions
* Will put a rough version of them in the next comment, so that you guys can test these changes and have notifications running
* If you're happy, then I can finalise

### CODE REVIEW

**Comment by myii** [comment]
## Notes
* Follow-up to #31
* For the setup: does not seem to be any problem if you have already installed gems - `bundler` seems to pick everything up

## Setup instructions
* For notifications to work properly, "you have to install the `libnotify-bin` package with your favorite package manager" (see https://github.com/guard/guard/wiki/System-notifications#libnotify); e.g.
```
$ sudo apt-get install libnotify-bin
```
* cd to main `taiga-doc` directory
* Install `bundler`:
```
$ gem install bundler
```
* `Gemfile` is already in place so install everything by simply running:
```
$ bundle
```
* `Guardfile` is already in place so ready to run:
```
$ bundle exec guard
```
* If you can't be bothered to keep running this command manually, say you want to play around with `Guardfile` for testing purposes, use:
```
$ while bundle exec guard; echo "Restarting guard..."; do echo; done
```
* If you use this loop method, be aware of:
    * Can no longer stop Guard with `Ctrl-D` alone; have to press `Ctrl-D` and then `Ctrl-C` in quick succession
    * DON'T switch branches with this Guard still running - the notifications will never end(!) - or you can kill them all at once with something like:
```
$ killall notify-osd
```
* And that's all for setup

## Trying it out
* `webhooks.adoc` still has an issue with a trailing comma on line 84
* Compare between saving the file with and without that comma - notifications should appear each time you save
* Make a few more naughty commas in different files
* Then run the `build-docs.sh` script to see the warnings

## There's more...
* But I'll wait until I get your feedback for the above...

**Comment by jespino** [comment]
I like it, to be more robust and generic you can replace rgrep with grep -r, becase in not debian based systems rgrep alias doesn't exist.

**Comment by myii** [comment]
@jespino: OK, have changed `rgrep` to `grep -r`.  Have also added an excludes file, in case you want a particular file to be ignored from the test because it shows an issue when there isn't one (false-positive).  Since `webhooks.adoc` still has an issue, you can add it to the excludes file and see that it is ignored from being tested, either from Guard or from the `build-docs.sh` script.

To reiterate, to get the notifications working properly, I had to run Guard using `bundle`.  Let me know how you get along.

**Comment by jespino** [comment]
I like it a lot. I think is enough the libnotify and terminal_title, if anybody needs more, can be added in the future.

If you think this is ready I can merge it :smile:

**Comment by myii** [comment]
@jespino: Please merge this.  When I get a chance, I will update `README.md` and send that in a new PR.

**Comment by jespino** [comment]
Thanks!

**Pull request merged**
