### PR TITLE
Correct text

### PR DESCRIPTION
**Pull request by pwmvx1289**

### CODE REVIEW

**Comment by jespino** [comment]
Thanks! :sparkles:

**Comment by pwmvx1289** [comment]
@jespino It is not taking effect are there errors with my changes?

**Comment by pwmvx1289** [comment]
@jespino It is not taking effect is there any error with my commit?

**Comment by jespino** [comment]
No, everything is ok, we haven uploaded it yet.

**Comment by wongalvis** [comment]
Noted thanks. :)

**Pull request merged**
